version: 0.2

phases:
  install:
    commands:
      - echo "Installing Httpd server"
      - sudo apt update
  build:
    commands:
      - echo "Build started"
      - sudo cp index.html /var/www/html/
  post_build:
    commands:
      - echo "Completed Successfully"


artifacts:
  files:
    - /var/www/html/index.html
